### PR TITLE
Allow user to choose font colors and BG image

### LINKED ISSUE #3: Optional font and background color
# About

There should be a set of **web-safe colors** to choose from and one should be able to change the font and background color easily, without changing the CSS code.

### PR DESCRIPTION
**Pull request by abettermap**
Closes #3

### CODE REVIEW

**Comment by abettermap** [comment]
Hi @smddzcy-  I believe the code is roughly where you wanted it except for the color list (our pending discussion in #3), which I will leave up to you. The "choosing a color by name" functionality is done though, but let me know if anything needs to be fixed!

**Comment by smddzcy** [comment]
Looks perfect! I think it just needs some comments, but I can do that. Merged 👍

**Comment by abettermap** [comment]
@smddzcy Cool, sounds good. And I should be able to finish #2 tomorrow.

**Comment by smddzcy** [comment]
@abettermap Alright, thank you!

**Pull request merged**
